.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.prettierrc
package.json
src/index.js
src/views/Reporting Rates/Overview/ReportingRatesOverview.js
src/views/Reporting Rates/Overview/ReportingRatesOverviewHeader.js
src/views/Reporting Rates/Overview/UploadsReportingConstistency.js
src/views/Reporting Rates/ReportingRates.js
src/views/Shared/Api.js
src/views/Shared/Filter.js
yarn.lock

adding expected upload functionality

adding expected upload functionality

---

package.json
src/views/Reporting Rates/Overview/ReportingRatesOverview.js
src/views/Reporting Rates/Overview/ReportingRatesTrends.js
src/views/Reporting Rates/Overview/UploadsReportingConstistency.js
src/views/Shared/Api.js
src/views/Shared/Filter.js
yarn.lock

Adds data to recency and consistency trend

add data to trend charts

---

src/views/Reporting Rates/Overview/ReportingRatesOverview.js
src/views/Reporting Rates/Overview/ReportingRatesTrends.js
src/views/Reporting Rates/Overview/UploadsReportingConstistency.js
src/views/Shared/Filter.js

- Add tab for each supported docket
- Update consistency chart color

add docket tabs

---

src/scss/_custom.scss
src/views/Reporting Rates/County/CountyReports.js
src/views/Reporting Rates/County/ReportingRatesByCounty.js
src/views/Reporting Rates/Overview/ReportingRatesOverview.js
src/views/Reporting Rates/Overview/ReportingRatesOverviewHeader.js
src/views/Reporting Rates/Partner/ReportingRatesByServiceDeliveryPartner.js
src/views/Reporting Rates/Partner/ServiceDeliveryPartnerReports.js
src/views/Reporting Rates/ReportingRates.js

charts for reporting rates by county and by partner

Reporting rates by county

---

src/views/Shared/Api.js

ensure that on production we call the https API

ensure that on production we use https

---

src/_nav.js
src/routes.js
src/views/Hts Overview/HtsOverview.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByAgeSex.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByCounty.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPartner.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPopulationType.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeMonthsSinceLastTest.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeOverviewFooter.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeOverviewHeader.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTBScreeningAndTBOutcome.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTestingStrategy.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTypeAndSelfTest.js
src/views/Hts Overview/HtsUptake/Overview/NumberTestedPositivity.js
src/views/Shared/Filter.js
src/views/Shared/HtsUptakeFilter.js

Implementation of HTS uptake frontend

hts uptake frontend

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByCounty.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPartner.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTypeAndSelfTest.js

1. HTS Uptake by county
2. HTS Uptake by partner
3. HTS Uptake by Type and Self Test

implementation for uptake by

---

src/views/Hts Overview/HtsUptake/Overview/NumberTestedPositivity.js

Number Positivity change axis and formatting

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPopulationType.js

Hts uptake by population type table

---

.gitignore
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPopulationType.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTestingStrategy.js
src/views/Shared/HtsUptakeFilter.js

re-organize hts filter

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByAgeSex.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByCounty.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByPartner.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTestingStrategy.js

corrections made to the charts affecting the axis and order

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeMonthsSinceLastTest.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTBScreeningAndTBOutcome.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTypeAndSelfTest.js
src/views/Hts Overview/HtsUptake/Overview/NumberTestedPositivity.js

Hts uptake - new and retest stack

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeMonthsSinceLastTest.js

months since last test

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeMonthsSinceLastTest.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTBScreeningAndTBOutcome.js
src/views/Hts Overview/HtsUptake/Overview/HtsUptakeTypeAndSelfTest.js

TB Screening

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByAgeSex.js

change of verb name

---

src/views/Hts Overview/HtsUptake/Overview/HtsUptakeByAgeSex.js

clear console

---

src/views/Hts Overview/HtsPositivityLinkage/LinkageByAgeSex.js
src/views/Hts Overview/HtsPositivityLinkage/LinkageByCounty.js
src/views/Hts Overview/HtsPositivityLinkage/LinkageByPartner.js
src/views/Hts Overview/HtsPositivityLinkage/LinkageByPopulationType.js
src/views/Hts Overview/HtsPositivityLinkage/NumberPositiveLinked.js

Modify UI to be uniform with HTS Uptake

ui modifications for uniformity

---

src/views/CT/CurrentOnART/CurrentOnART.js
src/views/CT/CurrentOnART/CurrentOnARTFooter.js
src/views/CT/CurrentOnART/CurrentOnARTHeader.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByAgeSex.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByCounty.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByPartner.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrDistributionByCounty.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrDistributionByPartner.js
src/views/CT/CurrentOnART/TrendsInTxCurr.js
src/views/CT/HIVTreatmentOverview.js

Current on ART Frontend:
1. Trends in Tx Curr
2. TX CURR BY AGE AND SEX
3. TX CURR DISTRIBUTION BY COUNTY
4. TX CURR DISTRIBUTION BY PARTNER
5. TX CURR BY COUNTY
6. TX CURR BY PARTNER

current on ART frontend dev

---

src/views/CT/CurrentOnART/CurrentOnARTTxCurrByAgeSex.js

1. Current on ART TX Curr by Age and Sex

current on ART

---

src/views/CT/Home/CTHomeStabilityStatusAndTrendsInDsd.js

Appointment duration by stability in active patients

---

src/views/CT/CurrentOnART/CurrentOnARTTxCurrByCounty.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByPartner.js

TX Curr by age groups and Partner Distribution

---

src/views/CT/CurrentOnART/CurrentOnARTTxCurrByCounty.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByPartner.js

add count for male and female

---

src/views/CT/CurrentOnART/CurrentOnARTTxCurrByCounty.js
src/views/CT/CurrentOnART/CurrentOnARTTxCurrByPartner.js

bug fix for male and female

---

src/views/CT/AdverseEvents/AdverseEvents.js
src/views/CT/AdverseEvents/AdverseEventsCausesAndActionsByDrugs.js
src/views/CT/AdverseEvents/AdverseEventsFooter.js
src/views/CT/AdverseEvents/AdverseEventsHeader.js
src/views/CT/AdverseEvents/AdverseEventsSeverity.js
src/views/CT/AdverseEvents/AdverseEventsSeverityLevels.js
src/views/CT/AdverseEvents/AdverseEventsTable.js
src/views/CT/AdverseEvents/AdverseEventsTiles.js
src/views/CT/HIVTreatmentOverview.js

Frontend for adverse Events

---

src/views/CT/AdverseEvents/AdverseEventsTiles.js

1. total adverse events
2. desegregated adverse events for adults and children

adverse events:

---

.idea/inspectionProfiles/Project_Default.xml
src/views/CT/AdverseEvents/AdverseEventsSeverity.js
src/views/Home/CTHomeStabilityStatusAndTrendsInDsd.js

ADVERSE EVENTS ACTIONS BY SEVERITY

Adverse events

---

src/views/CT/AdverseEvents/AdverseEventsCausesAndActionsByDrugs.js

adverse events implementation:

---

src/views/CT/AdverseEvents/AdverseEventsSeverity.js
src/views/CT/AdverseEvents/AdverseEventsTiles.js
src/views/Shared/CTFilter.js

1. adverse events reported adults and children

---

src/views/CT/AdverseEvents/AdverseEventsTiles.js

1. adverse events number of adults and children with AE

---

src/views/CT/AdverseEvents/AdverseEventsTable.js

1. adverse events distribution by severity

---

src/routes.js

1. make resources not protected

---

src/views/CT/CurrentOnART/CurrentOnART.js
src/views/CT/CurrentOnART/CurrentOnARTTiles.js

1. update current on ART to include tiles

---

src/views/CT/CurrentOnART/CurrentOnARTTiles.js
src/views/CT/NewOnArt/NewOnARTTiles.js
src/views/CT/NewOnArt/NewOnArt.js

1. implement newly started tiles and desegregation

---

src/views/CT/NewOnArt/NewOnARTTiles.js
src/views/CT/NewOnArt/NewOnArt.js

1. bug fix newly started and ensure filter works for tiles

---

src/App.scss
src/containers/DefaultLayout/DefaultHeader.js
src/routes.js
src/views/Administration/Organizations/Organizations.js
src/views/Shared/Api.js

1. add edit and delete organizations

---

src/views/CT/CurrentOnART/CurrentOnARTTiles.js

1. resolve bug on viral suppression percentage

---

src/views/HTS/Uptake/UptakeByCounty.js
src/views/HTS/Uptake/UptakeByPartner.js
src/views/HTS/Uptake/UptakeByPopulationType.js
src/views/HTS/Uptake/UptakeNumberTestedAndPositivity.js
src/views/HTS/Uptake/UptakeOverview.js
src/views/HTS/Uptake/UptakeTestingStrategy.js

1. update labels in hts uptake

---

src/views/CT/AdverseEvents/AdverseEventsCausesAndActionsByDrugs.js

1. resolve reported causes of AES on mouse over

---

src/index.css
src/views/HTS/Uptake/UptakeByCounty.js
src/views/HTS/Uptake/UptakeByPartner.js

1. capitalize the first letter only for county and partners

---

src/views/HTS/Linkage/LinkageByAgeSex.js
src/views/HTS/Linkage/LinkageByCounty.js
src/views/HTS/Linkage/LinkageByPartner.js
src/views/HTS/Linkage/LinkageByPopulationType.js
src/views/HTS/Linkage/LinkageByStrategyEntryPoint.js
src/views/HTS/Linkage/LinkageNumberPositive.js
src/views/HTS/Uptake/UptakeByAgeSex.js

Feedbackbugfixes

---

src/views/HTS/Linkage/LinkageNumberPositive.js

1. resolve linkage by month data on months not showing properly

---

src/views/CT/AdverseEvents/AdverseEventsTiles.js

1. put commas in AE's

---

src/views/CT/AdverseEvents/AdverseEvents.js
src/views/CT/AdverseEvents/AdverseEventsCausesAndActionsByDrugs.js

1. AE feedback

---

src/views/HTS/Uptake/UptakeByAgeSex.js
src/views/HTS/Uptake/UptakeByCounty.js
src/views/HTS/Uptake/UptakeByPartner.js
src/views/HTS/Uptake/UptakeByPopulationType.js
src/views/HTS/Uptake/UptakeMonthsSinceLastTest.js
src/views/HTS/Uptake/UptakeOverview.js
src/views/HTS/Uptake/UptakeTBScreeningAndTBOutcome.js
src/views/HTS/Uptake/UptakeTestingStrategy.js
src/views/HTS/Uptake/UptakeTypeAndSelfTest.js

1. uptake ensure the default year is today

---

src/views/HTS/Uptake/UptakeNumberTestedAndPositivity.js
src/views/HTS/Uptake/UptakeTypeAndSelfTest.js
src/views/Shared/UniversalFilter.js

1. make filter searchable

---

src/views/RR/RR.js
src/views/RR/RRCounty.js
src/views/RR/RRPartner.js

1. refactor reporting rates charts and add colors

---

.idea/inspectionProfiles/Project_Default.xml
src/containers/DefaultLayout/DefaultHeader.js
src/routes.js
src/utils/authProvider.js
src/views/Users/Profile.js

1. feedback for login and profile functionality

---

public/index.html
src/services/UserService.js

1. change favicon

---

src/App.js
src/services/UserService.js
src/views/HTS/Uptake/UptakeTBScreeningAndTBOutcome.js
src/views/RR/RROverview.js

1. tb screening bug fix

---

src/views/Home/HomeSexDistribution.js
src/views/Home/HomeVLCascade.js

1. fix NAN error on homepage

---

src/containers/DefaultLayout/DefaultHeader.js
src/index.css
src/views/HTS/PNS/PNSContactsTestingOverview.js
src/views/HTS/PNS/PNSFamilyTestingOverview.js
src/views/Home/HomeVLCascade.js
src/views/RR/RROverview.js
src/views/Shared/Api.js

1. ensure menus are bold on nascop dwh

---

src/views/CT/AdverseEvents/AdverseEventsSeverityLevels.js

1. show only AE categories where total for all is greater than 0

---

src/scss/_custom.scss
src/selectors/CT/Dsd/dsdAppointmentDurationBySex.js
src/selectors/CT/Dsd/dsdAppointmentDurationByStabilityStatus.js
src/views/CT/DSD/AppointmentDurationBySex.js
src/views/CT/DSD/AppointmentDurationByStability.js
src/views/CT/DSD/DSD.js
src/views/CT/DSD/DSDIndicatorDefinition.js

updates for MMD UPTAKE BY STABILITY STATUS AND MMD UPTAKE BY SEX

---

src/selectors/CT/Dsd/dsdAppointmentDurationByAge.js
src/selectors/CT/Dsd/dsdStabilityStatusByAgeSex.js
src/selectors/CT/Dsd/dsdStabilityStatusByCounty.js
src/selectors/CT/Dsd/dsdStabilityStatusByPartner.js
src/selectors/CT/Dsd/dsdStableMmdModels.js
src/views/CT/DSD/AppointmentDurationByAge.js
src/views/CT/DSD/AppointmentDurationStableByCounty.js
src/views/CT/DSD/AppointmentDurationStableByPartner.js
src/views/CT/DSD/DSD.js
src/views/CT/DSD/DistributionMMDStable.js
src/views/CT/DSD/DistributionStableAgeSex.js
src/views/CT/DSD/DistributionStableByCounty.js
src/views/CT/DSD/DistributionStableByPartner.js
src/views/CT/DSD/DistributionUnstable.js

DSD changes and updates according to recommended mock ups

---

src/selectors/CT/Dsd/dsdAppointmentDurationByAge.js

check if array has values before accessing it

---

src/views/CT/DSD/DistributionStableByPartner.js

update DistributionStableByPartner.js labels

---

src/views/CT/ArtOptimization/AdultTldUptakeByCounty.js

update tld uptake by county to be descending

---

src/views/CT/DSD/DSDIndicatorDefinition.js

update indicator definitions

---

src/views/CT/DSD/DistributionMMDStable.js
src/views/CT/DSD/DistributionUnstable.js

update charts remove top number and include it in the tooltip

---

src/views/CT/DSD/AppointmentDurationBySex.js
src/views/CT/DSD/AppointmentDurationByStability.js

change columns for columns

---

src/selectors/CT/Dsd/dsdStabilityStatusByCounty.js
src/selectors/CT/Dsd/dsdStabilityStatusByPartner.js
src/views/CT/DSD/DistributionStableByCounty.js
src/views/CT/DSD/DistributionStableByPartner.js

update DistributionStableByCounty.js and DistributionStableByPartner.js

---

src/views/CT/ArtOptimization/AdultTldUptakeByPartner.js

reorder tlduptake by partner

---

src/views/CT/ViralLoad/ViralLoad.js

remove linelist

---

src/views/CT/DSD/DistributionUnstable.js

hot fix for pregnant and breastfeeding

---

src/selectors/CT/ViralLoad/medianTimeTo1stVlByYear.js

median time to first vl

---

src/views/CT/AdverseEvents/AdverseEvents.js
src/views/CT/AdverseEvents/AdverseEventsProportionOfPlHivWithAeRegimenChanged.js

show the ae changed, stopped and not altered in a single row

---

src/views/CT/AdverseEvents/AdverseEvents.js

remove incomplete chart from portal

---

src/views/CT/CT.js

ensure viralLoadSuppressionByCategory Is Loaded On Tab Click

---

src/selectors/CT/CurrentOnArt/currentOnArtByAgeSex.js

remove space in age groups

---

src/views/Home/HomeAgeDistribution.js

resolve interchanged numbers

---

src/views/CT/ViralLoad/ViralLoadSuppressionByYear.js

change title: Levels of Viral suppression by year of ART

---

src/selectors/CT/NewOnArt/medianTimeToArtStartByCounty.js
src/selectors/CT/NewOnArt/medianTimeToArtStartByPartner.js
src/selectors/CT/NewOnArt/medianTimeToArtStartByYear.js
src/views/CT/ArtOptimization/AdultTldUptakeByAgeGender.js
src/views/CT/ArtOptimization/ChildDistributionRegimens.js
src/views/CT/NewOnArt/MedianTimeToArtStartByCounty.js
src/views/CT/NewOnArt/MedianTimeToArtStartByPartner.js
src/views/CT/NewOnArt/MedianTimeToArtStartByYear.js
src/views/CT/NewOnArt/NewOnArt.js

TLD UPTAKE BY AGE AND GENDER AMONG PATIENTS CURRENT ON ART,
MEDIAN TIME TO ART START BY YEAR OF ART START,
MEDIAN TIME TO ART START BY COUNTY,
MEDIAN TIME TO ART START BY PARTNER

PROPORTION OF CALHIV BY REGIMEN,

---

src/views/CT/DSD/DSD.js

dsd MMD UPTAKE BY AGE GROUP move it up

---

src/selectors/CT/NewOnArt/newOnArtTrends.js
src/views/CT/NewOnArt/NewOnArtTrends.js

add tx new tooltip male and female

---

src/views/HTS/Uptake/HtsUptakeIndicatorDefinition.js
src/views/HTS/Uptake/Uptake.js

indicator definition for hts uptake

---

src/views/CT/NewOnArt/MedianTimeToArtStartByCounty.js
src/views/CT/NewOnArt/MedianTimeToArtStartByPartner.js
src/views/CT/NewOnArt/MedianTimeToArtStartByYear.js

update mediantimetoartstart to be by days

---

src/scss/_custom.scss
src/views/RR/RR.js
src/views/RR/RRIndicatorDefinition.js
src/views/RR/RROverview.js

add indicator definition for reporting rates

---

src/views/RR/RRCounty.js
src/views/RR/RRPartner.js

resolve consistency of reporting error

---

src/views/RR/RROverview.js

resolve error on reporting rates percentage being greater than 100%

---

src/selectors/CT/NewOnArt/newOnArtHtsPositive.js

NEW ON TREATMENT COMPARED TO HTS POSITIVES

---

src/views/Home/Home.js

remove mmd charts from homepage

remove mmd charts from homepage

---

.editorconfig
.idea/inspectionProfiles/Project_Default.xml
src/actions/CT/AdverseEvents/adverseEventsSeverityGradingActions.js
src/selectors/AgeGroupsArray.js
src/selectors/CT/AdverseEvents/adverseEventsSeverityActions.js
src/selectors/CT/AdverseEvents/adverseEventsSeverityGrading.js
src/views/CT/AdverseEvents/AdverseEvents.js
src/views/CT/AdverseEvents/AdverseEventsSeverityActions.js
src/views/CT/AdverseEvents/AdverseEventsSeverityGrading.js

CALHIV - ADVERSE EVENTS ACTIONS BY SEVERITY

CALHIV - SEVERITY GRADING OF AEs

---

src/selectors/CT/AdverseEvents/adverseEventsActionsByDrugs.js
src/selectors/CT/AdverseEvents/adverseEventsActionsByDrugsNew.js
src/views/CT/AdverseEvents/AdverseEvents.js
src/views/CT/AdverseEvents/AdverseEventsActionsByDrugs.js
src/views/CT/AdverseEvents/AdverseEventsCauses.js
src/views/CT/AdverseEvents/AdverseEventsProportionOfPlHivByTypeOfSuspectedCausativeDrugs.js
src/views/CT/AdverseEvents/AdverseEventsProportionOfPlHivWithAeRelatedToArtOrSuspectedArt.js

CALHIV - ADVERSE EVENTS ACTIONS BY DRUGS

CALHIV - REPORTED CAUSES OF AEs

---

src/selectors/CT/OTZ/otzProportionOfAlHivEnrolledInOtzWhoHaveCompletedTrainingByCounty.js
src/selectors/CT/OTZ/otzProportionOfAlHivEnrolledInOtzWhoHaveCompletedTrainingByPartner.js

- Proportion of ALHIV enrolled in OTZ who have completed OTZ training BY county
- Proportion of ALHIV enrolled in OTZ who have completed OTZ training BY partner

implementation for

---

src/selectors/CT/TreatmentOutcomes/sixMonthRetention.js
src/selectors/CT/TreatmentOutcomes/threeMonthRetention.js
src/selectors/CT/TreatmentOutcomes/twelveMonthRetention.js
src/selectors/CT/TreatmentOutcomes/twentyFourMonthRetention.js
src/views/CT/TreatmentOutcomes/SixMonthRetention.js
src/views/CT/TreatmentOutcomes/ThreeMonthRetention.js
src/views/CT/TreatmentOutcomes/TwelveMonthRetention.js
src/views/CT/TreatmentOutcomes/TwentyFourMonthRetention.js

- 6 MONTH RETENTION BY YEAR OF ART START*
- 12 MONTH RETENTION BY YEAR OF ART START*
- 18 MONTH RETENTION BY YEAR OF ART START*

- 3 MONTH RETENTION BY YEAR OF ART START*

---

src/selectors/CT/Covid/covidAdultPLHIVVaccinatedByAgeGroup.js
src/selectors/CT/Covid/covidAdultPLHIVVaccinatedByCounty.js
src/selectors/CT/Covid/covidAdultPLHIVVaccinatedByGender.js
src/selectors/CT/Covid/covidAdultPLHIVVaccinatedByPartner.js
src/selectors/CT/Covid/covidTrendsPLHIVVaccinationInTheLast12Months.js
src/views/CT/Covid/COVIDAdultPLHIVVaccinatedByAge.js
src/views/CT/Covid/COVIDAdultPLHIVVaccinatedByCounty.js
src/views/CT/Covid/COVIDAdultPLHIVVaccinatedByGender.js
src/views/CT/Covid/COVIDAdultPLHIVVaccinatedByPartner.js
src/views/CT/Covid/COVIDAdultPlhivCurrentOnTreatment.js
src/views/CT/Covid/COVIDFullyVaccinated.js
src/views/CT/Covid/COVIDNumberScreened.js
src/views/CT/Covid/COVIDOverview.js
src/views/CT/Covid/COVIDPLHIVCurrentOnART.js
src/views/CT/Covid/COVIDPLHIVEverHadInfection.js
src/views/CT/Covid/COVIDPLHIVWhoHadSymptomaticInfection.js
src/views/CT/Covid/COVIDPartiallyVaccinated.js
src/views/CT/Covid/COVIDTrendsOfAdultPLHIVVaccinationInTheLast12Months.js

Added donut charts and not vaccinated charts

Updates on covid charts

---

public/index.html
src/views/CT/Covid/COVIDAdultPlhivCurrentOnTreatment.js
src/views/CT/Covid/COVIDFullyVaccinated.js
src/views/CT/Covid/COVIDNumberScreened.js
src/views/CT/Covid/COVIDPartiallyVaccinated.js
src/views/CT/Covid/COVIDTabs.js

Reverts palladiumkenya/dwh-portal#530

Revert "Ui changes to covid donuts"

---

src/selectors/Operational&HIS/Comparison/currStartedOnArtByFacilityPartnerKHIS.js
src/selectors/Operational&HIS/Comparison/newStartedOnArtByFacilityPartnerKHIS.js
src/views/CT/ViralLoad/MedianTimeTo1stVlByCounty.js
src/views/CT/ViralLoad/MedianTimeTo1stVlByPartner.js
src/views/CT/ViralLoad/MedianTimeTo1stVlByYear.js

comparison tables to reflect on agegroup filters

commented out footer text on vl uptake

---

src/containers/DefaultLayout/DefaultHeader.js
src/selectors/CT/ArtVerification/pendingSurveys.js
src/views/CT/ArtVerification/ArtVerificationPendingSurveysByCounty.js
src/views/CT/ArtVerification/ArtVerificationPendingSurveysByPartner.js
src/views/CT/CT.js
src/views/HTS/HTS.js
src/views/Operational&HIS/OperationalHIS.js
src/views/RR/RR.js
src/views/Shared/UniversalFilter.js

Updated pending survey charts

---

src/selectors/PMTCTRRI/MissedInfantProphylaxis.js
src/views/PMTCTRRI/missedInfantProf/MissedInfantProfOverview.js

update from infant prophylaxis api

---

src/containers/DefaultLayout/DefaultHeader.js
src/routes.js

- Added Tafsiri to self service tools

Added Tafsiri Self service tool

---

src/views/Tafsiri/Tafsiri.js

Update comment Tafsiri.js
